// The layout file is the main entry point of the application, any changes added to the body of this page will show up on all routes in the website

import "@styles/globals.css";
import Nav from "./components/Nav";
import Provider from './components/Provider';
import Footer from "./components/Footer";

export const metadata = {
  title: "supplyChain",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className="w-full bg-gradient-to-b from-green-200 to-green-500">
        <Provider>
          <main className='app'>
            <Nav />
            {children}
            <Footer />
          </main>
        </Provider>
      </body>
    </html>
  );
}
