// The layout file is the main entry point of the application, any changes added to the body of this page will show up on all routes in the website

import "@styles/globals.css";
import Nav from "./components/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <main className='app'>
          <Nav />
          {children}
          {/* footer here */}
        </main>
      </body>
    </html>
  );
}
