// The layout file is the main entry point of the application, any changes added to the body of this page will show up on all routes in the website

import "@styles/globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className="h-screen bg-gradient-to-b from-green-200 to-green-500">
        <main className='app'>
          <Nav />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
